// Auto-generated by `supabase gen types typescript --linked`.
// Regenerate with `pnpm regen:types` after applying new migrations.
// Do not edit by hand.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5";
  };
  public: {
    Tables: {
      briefs: {
        Row: {
          brief_id_human: string;
          client_id: string | null;
          created_at: string;
          decided_at: string | null;
          decided_by: string | null;
          decided_notes: string | null;
          id: string;
          payload: Json;
          posted_at: string | null;
          status: Database["public"]["Enums"]["brief_status"];
        };
        Insert: {
          brief_id_human: string;
          client_id?: string | null;
          created_at?: string;
          decided_at?: string | null;
          decided_by?: string | null;
          decided_notes?: string | null;
          id?: string;
          payload: Json;
          posted_at?: string | null;
          status?: Database["public"]["Enums"]["brief_status"];
        };
        Update: {
          brief_id_human?: string;
          client_id?: string | null;
          created_at?: string;
          decided_at?: string | null;
          decided_by?: string | null;
          decided_notes?: string | null;
          id?: string;
          payload?: Json;
          posted_at?: string | null;
          status?: Database["public"]["Enums"]["brief_status"];
        };
        Relationships: [
          {
            foreignKeyName: "briefs_client_id_fkey";
            columns: ["client_id"];
            isOneToOne: false;
            referencedRelation: "clients";
            referencedColumns: ["id"];
          },
        ];
      };
      campaign_perf_image: {
        Row: {
          campaign_id: string;
          clicks: number | null;
          client_id: string | null;
          cpl_real: number | null;
          ctr: number | null;
          freq: number | null;
          id: string;
          impressions: number | null;
          leads_ghl: number | null;
          leads_meta: number | null;
          pulled_at: string;
          spend: number | null;
          verdict: Database["public"]["Enums"]["ad_verdict"] | null;
          verdict_reason: string | null;
          window_days: number;
        };
        Insert: {
          campaign_id: string;
          clicks?: number | null;
          client_id?: string | null;
          cpl_real?: number | null;
          ctr?: number | null;
          freq?: number | null;
          id?: string;
          impressions?: number | null;
          leads_ghl?: number | null;
          leads_meta?: number | null;
          pulled_at?: string;
          spend?: number | null;
          verdict?: Database["public"]["Enums"]["ad_verdict"] | null;
          verdict_reason?: string | null;
          window_days: number;
        };
        Update: {
          campaign_id?: string;
          clicks?: number | null;
          client_id?: string | null;
          cpl_real?: number | null;
          ctr?: number | null;
          freq?: number | null;
          id?: string;
          impressions?: number | null;
          leads_ghl?: number | null;
          leads_meta?: number | null;
          pulled_at?: string;
          spend?: number | null;
          verdict?: Database["public"]["Enums"]["ad_verdict"] | null;
          verdict_reason?: string | null;
          window_days?: number;
        };
        Relationships: [
          {
            foreignKeyName: "campaign_perf_image_client_id_fkey";
            columns: ["client_id"];
            isOneToOne: false;
            referencedRelation: "clients";
            referencedColumns: ["id"];
          },
        ];
      };
      campaign_perf_video: {
        Row: {
          campaign_id: string;
          clicks: number | null;
          client_id: string | null;
          cpl_real: number | null;
          ctr: number | null;
          drop_off_3s: number | null;
          freq: number | null;
          hook_rate: number | null;
          id: string;
          impressions: number | null;
          leads_ghl: number | null;
          leads_meta: number | null;
          pulled_at: string;
          spend: number | null;
          verdict: Database["public"]["Enums"]["ad_verdict"] | null;
          verdict_reason: string | null;
          view_rate_avg: number | null;
          watch_time_p50: number | null;
          window_days: number;
        };
        Insert: {
          campaign_id: string;
          clicks?: number | null;
          client_id?: string | null;
          cpl_real?: number | null;
          ctr?: number | null;
          drop_off_3s?: number | null;
          freq?: number | null;
          hook_rate?: number | null;
          id?: string;
          impressions?: number | null;
          leads_ghl?: number | null;
          leads_meta?: number | null;
          pulled_at?: string;
          spend?: number | null;
          verdict?: Database["public"]["Enums"]["ad_verdict"] | null;
          verdict_reason?: string | null;
          view_rate_avg?: number | null;
          watch_time_p50?: number | null;
          window_days: number;
        };
        Update: {
          campaign_id?: string;
          clicks?: number | null;
          client_id?: string | null;
          cpl_real?: number | null;
          ctr?: number | null;
          drop_off_3s?: number | null;
          freq?: number | null;
          hook_rate?: number | null;
          id?: string;
          impressions?: number | null;
          leads_ghl?: number | null;
          leads_meta?: number | null;
          pulled_at?: string;
          spend?: number | null;
          verdict?: Database["public"]["Enums"]["ad_verdict"] | null;
          verdict_reason?: string | null;
          view_rate_avg?: number | null;
          watch_time_p50?: number | null;
          window_days?: number;
        };
        Relationships: [
          {
            foreignKeyName: "campaign_perf_video_client_id_fkey";
            columns: ["client_id"];
            isOneToOne: false;
            referencedRelation: "clients";
            referencedColumns: ["id"];
          },
        ];
      };
      clients: {
        Row: {
          brand_colors: Json | null;
          cpl_target: number | null;
          created_at: string;
          drive_root_folder_id: string | null;
          ghl_location_id: string | null;
          id: string;
          meta_account_id: string | null;
          name: string;
          service_type: Database["public"]["Enums"]["service_type"];
          slug: string;
          status: string;
          updated_at: string;
        };
        Insert: {
          brand_colors?: Json | null;
          cpl_target?: number | null;
          created_at?: string;
          drive_root_folder_id?: string | null;
          ghl_location_id?: string | null;
          id?: string;
          meta_account_id?: string | null;
          name: string;
          service_type: Database["public"]["Enums"]["service_type"];
          slug: string;
          status?: string;
          updated_at?: string;
        };
        Update: {
          brand_colors?: Json | null;
          cpl_target?: number | null;
          created_at?: string;
          drive_root_folder_id?: string | null;
          ghl_location_id?: string | null;
          id?: string;
          meta_account_id?: string | null;
          name?: string;
          service_type?: Database["public"]["Enums"]["service_type"];
          slug?: string;
          status?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      copy_variants: {
        Row: {
          body: string | null;
          created_at: string;
          creative_id: string;
          cta: string | null;
          headline: string | null;
          humanized: boolean | null;
          id: string;
          status: string | null;
        };
        Insert: {
          body?: string | null;
          created_at?: string;
          creative_id: string;
          cta?: string | null;
          headline?: string | null;
          humanized?: boolean | null;
          id?: string;
          status?: string | null;
        };
        Update: {
          body?: string | null;
          created_at?: string;
          creative_id?: string;
          cta?: string | null;
          headline?: string | null;
          humanized?: boolean | null;
          id?: string;
          status?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "copy_variants_creative_id_fkey";
            columns: ["creative_id"];
            isOneToOne: false;
            referencedRelation: "creatives";
            referencedColumns: ["id"];
          },
        ];
      };
      creative_iterations: {
        Row: {
          author: Database["public"]["Enums"]["iteration_author"];
          content: Json | null;
          created_at: string;
          creative_id: string;
          id: string;
          image_path_supabase: string | null;
          kind: Database["public"]["Enums"]["image_iteration_kind"];
          parent_creative_id: string | null;
        };
        Insert: {
          author: Database["public"]["Enums"]["iteration_author"];
          content?: Json | null;
          created_at?: string;
          creative_id: string;
          id?: string;
          image_path_supabase?: string | null;
          kind: Database["public"]["Enums"]["image_iteration_kind"];
          parent_creative_id?: string | null;
        };
        Update: {
          author?: Database["public"]["Enums"]["iteration_author"];
          content?: Json | null;
          created_at?: string;
          creative_id?: string;
          id?: string;
          image_path_supabase?: string | null;
          kind?: Database["public"]["Enums"]["image_iteration_kind"];
          parent_creative_id?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "creative_iterations_creative_id_fkey";
            columns: ["creative_id"];
            isOneToOne: false;
            referencedRelation: "creatives";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "creative_iterations_parent_creative_id_fkey";
            columns: ["parent_creative_id"];
            isOneToOne: false;
            referencedRelation: "creatives";
            referencedColumns: ["id"];
          },
        ];
      };
      creatives: {
        Row: {
          approved_at: string | null;
          brief_id: string;
          concept: string | null;
          created_at: string;
          file_path_drive: string | null;
          file_path_supabase: string | null;
          id: string;
          offer_text: string | null;
          prompt_used: Json | null;
          ratio: Database["public"]["Enums"]["ratio"] | null;
          status: Database["public"]["Enums"]["image_creative_status"];
          type: Database["public"]["Enums"]["creative_type"];
          version: string;
        };
        Insert: {
          approved_at?: string | null;
          brief_id: string;
          concept?: string | null;
          created_at?: string;
          file_path_drive?: string | null;
          file_path_supabase?: string | null;
          id?: string;
          offer_text?: string | null;
          prompt_used?: Json | null;
          ratio?: Database["public"]["Enums"]["ratio"] | null;
          status?: Database["public"]["Enums"]["image_creative_status"];
          type?: Database["public"]["Enums"]["creative_type"];
          version?: string;
        };
        Update: {
          approved_at?: string | null;
          brief_id?: string;
          concept?: string | null;
          created_at?: string;
          file_path_drive?: string | null;
          file_path_supabase?: string | null;
          id?: string;
          offer_text?: string | null;
          prompt_used?: Json | null;
          ratio?: Database["public"]["Enums"]["ratio"] | null;
          status?: Database["public"]["Enums"]["image_creative_status"];
          type?: Database["public"]["Enums"]["creative_type"];
          version?: string;
        };
        Relationships: [
          {
            foreignKeyName: "creatives_brief_id_fkey";
            columns: ["brief_id"];
            isOneToOne: false;
            referencedRelation: "briefs";
            referencedColumns: ["id"];
          },
        ];
      };
      events: {
        Row: {
          created_at: string;
          id: string;
          kind: string;
          payload: Json | null;
          ref_id: string | null;
          ref_table: string | null;
        };
        Insert: {
          created_at?: string;
          id?: string;
          kind: string;
          payload?: Json | null;
          ref_id?: string | null;
          ref_table?: string | null;
        };
        Update: {
          created_at?: string;
          id?: string;
          kind?: string;
          payload?: Json | null;
          ref_id?: string | null;
          ref_table?: string | null;
        };
        Relationships: [];
      };
      launch_packages: {
        Row: {
          brief_id: string;
          created_at: string;
          decided_at: string | null;
          decided_notes: string | null;
          id: string;
          payload: Json;
          status: string;
        };
        Insert: {
          brief_id: string;
          created_at?: string;
          decided_at?: string | null;
          decided_notes?: string | null;
          id?: string;
          payload: Json;
          status?: string;
        };
        Update: {
          brief_id?: string;
          created_at?: string;
          decided_at?: string | null;
          decided_notes?: string | null;
          id?: string;
          payload?: Json;
          status?: string;
        };
        Relationships: [
          {
            foreignKeyName: "launch_packages_brief_id_fkey";
            columns: ["brief_id"];
            isOneToOne: false;
            referencedRelation: "briefs";
            referencedColumns: ["id"];
          },
        ];
      };
      overrides: {
        Row: {
          corrected_value: Json;
          edited_at: string;
          edited_by: string;
          field_name: string;
          id: string;
          row_id: string;
          table_name: string;
        };
        Insert: {
          corrected_value: Json;
          edited_at?: string;
          edited_by?: string;
          field_name: string;
          id?: string;
          row_id: string;
          table_name: string;
        };
        Update: {
          corrected_value?: Json;
          edited_at?: string;
          edited_by?: string;
          field_name?: string;
          id?: string;
          row_id?: string;
          table_name?: string;
        };
        Relationships: [];
      };
      push_subscriptions: {
        Row: {
          created_at: string;
          endpoint: string;
          id: string;
          keys: Json;
          last_seen: string | null;
        };
        Insert: {
          created_at?: string;
          endpoint: string;
          id?: string;
          keys: Json;
          last_seen?: string | null;
        };
        Update: {
          created_at?: string;
          endpoint?: string;
          id?: string;
          keys?: Json;
          last_seen?: string | null;
        };
        Relationships: [];
      };
      sync_log: {
        Row: {
          error_text: string | null;
          finished_at: string | null;
          id: string;
          payload: Json | null;
          rows_upserted: number | null;
          source: string;
          started_at: string;
          status: Database["public"]["Enums"]["sync_status"];
        };
        Insert: {
          error_text?: string | null;
          finished_at?: string | null;
          id?: string;
          payload?: Json | null;
          rows_upserted?: number | null;
          source: string;
          started_at?: string;
          status?: Database["public"]["Enums"]["sync_status"];
        };
        Update: {
          error_text?: string | null;
          finished_at?: string | null;
          id?: string;
          payload?: Json | null;
          rows_upserted?: number | null;
          source?: string;
          started_at?: string;
          status?: Database["public"]["Enums"]["sync_status"];
        };
        Relationships: [];
      };
      video_briefs: {
        Row: {
          brief_id_human: string;
          broll_selection_mode: string;
          captions_style: string | null;
          client_id: string | null;
          created_at: string;
          decided_at: string | null;
          decided_by: string | null;
          decided_notes: string | null;
          dimensions: Database["public"]["Enums"]["ratio"] | null;
          hook_style: string | null;
          id: string;
          music_track: string | null;
          payload: Json | null;
          posted_at: string | null;
          script_outline: Json | null;
          status: Database["public"]["Enums"]["video_brief_status"];
          target_duration_s: number | null;
          voice_id: string | null;
        };
        Insert: {
          brief_id_human: string;
          broll_selection_mode?: string;
          captions_style?: string | null;
          client_id?: string | null;
          created_at?: string;
          decided_at?: string | null;
          decided_by?: string | null;
          decided_notes?: string | null;
          dimensions?: Database["public"]["Enums"]["ratio"] | null;
          hook_style?: string | null;
          id?: string;
          music_track?: string | null;
          payload?: Json | null;
          posted_at?: string | null;
          script_outline?: Json | null;
          status?: Database["public"]["Enums"]["video_brief_status"];
          target_duration_s?: number | null;
          voice_id?: string | null;
        };
        Update: {
          brief_id_human?: string;
          broll_selection_mode?: string;
          captions_style?: string | null;
          client_id?: string | null;
          created_at?: string;
          decided_at?: string | null;
          decided_by?: string | null;
          decided_notes?: string | null;
          dimensions?: Database["public"]["Enums"]["ratio"] | null;
          hook_style?: string | null;
          id?: string;
          music_track?: string | null;
          payload?: Json | null;
          posted_at?: string | null;
          script_outline?: Json | null;
          status?: Database["public"]["Enums"]["video_brief_status"];
          target_duration_s?: number | null;
          voice_id?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "video_briefs_client_id_fkey";
            columns: ["client_id"];
            isOneToOne: false;
            referencedRelation: "clients";
            referencedColumns: ["id"];
          },
        ];
      };
      video_copy_variants: {
        Row: {
          body: string | null;
          created_at: string;
          creative_id: string;
          cta: string | null;
          headline: string | null;
          humanized: boolean | null;
          id: string;
          status: string | null;
        };
        Insert: {
          body?: string | null;
          created_at?: string;
          creative_id: string;
          cta?: string | null;
          headline?: string | null;
          humanized?: boolean | null;
          id?: string;
          status?: string | null;
        };
        Update: {
          body?: string | null;
          created_at?: string;
          creative_id?: string;
          cta?: string | null;
          headline?: string | null;
          humanized?: boolean | null;
          id?: string;
          status?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "video_copy_variants_creative_id_fkey";
            columns: ["creative_id"];
            isOneToOne: false;
            referencedRelation: "video_creatives";
            referencedColumns: ["id"];
          },
        ];
      };
      video_creatives: {
        Row: {
          approved_at: string | null;
          brief_id: string;
          broll_clips: Json | null;
          captioned_path: string | null;
          composed_path: string | null;
          created_at: string;
          drive_url: string | null;
          duration_actual_s: number | null;
          id: string;
          script_path: string | null;
          status: Database["public"]["Enums"]["video_creative_status"];
          version: number;
          voiceover_path: string | null;
        };
        Insert: {
          approved_at?: string | null;
          brief_id: string;
          broll_clips?: Json | null;
          captioned_path?: string | null;
          composed_path?: string | null;
          created_at?: string;
          drive_url?: string | null;
          duration_actual_s?: number | null;
          id?: string;
          script_path?: string | null;
          status?: Database["public"]["Enums"]["video_creative_status"];
          version?: number;
          voiceover_path?: string | null;
        };
        Update: {
          approved_at?: string | null;
          brief_id?: string;
          broll_clips?: Json | null;
          captioned_path?: string | null;
          composed_path?: string | null;
          created_at?: string;
          drive_url?: string | null;
          duration_actual_s?: number | null;
          id?: string;
          script_path?: string | null;
          status?: Database["public"]["Enums"]["video_creative_status"];
          version?: number;
          voiceover_path?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "video_creatives_brief_id_fkey";
            columns: ["brief_id"];
            isOneToOne: false;
            referencedRelation: "video_briefs";
            referencedColumns: ["id"];
          },
        ];
      };
      video_iterations: {
        Row: {
          author: Database["public"]["Enums"]["iteration_author"];
          content: Json | null;
          created_at: string;
          creative_id: string;
          id: string;
          image_path_supabase: string | null;
          kind: Database["public"]["Enums"]["video_iteration_kind"];
          parent_creative_id: string | null;
        };
        Insert: {
          author: Database["public"]["Enums"]["iteration_author"];
          content?: Json | null;
          created_at?: string;
          creative_id: string;
          id?: string;
          image_path_supabase?: string | null;
          kind: Database["public"]["Enums"]["video_iteration_kind"];
          parent_creative_id?: string | null;
        };
        Update: {
          author?: Database["public"]["Enums"]["iteration_author"];
          content?: Json | null;
          created_at?: string;
          creative_id?: string;
          id?: string;
          image_path_supabase?: string | null;
          kind?: Database["public"]["Enums"]["video_iteration_kind"];
          parent_creative_id?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "video_iterations_creative_id_fkey";
            columns: ["creative_id"];
            isOneToOne: false;
            referencedRelation: "video_creatives";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "video_iterations_parent_creative_id_fkey";
            columns: ["parent_creative_id"];
            isOneToOne: false;
            referencedRelation: "video_creatives";
            referencedColumns: ["id"];
          },
        ];
      };
      video_launch_packages: {
        Row: {
          brief_id: string;
          created_at: string;
          decided_at: string | null;
          decided_notes: string | null;
          id: string;
          payload: Json;
          status: string;
        };
        Insert: {
          brief_id: string;
          created_at?: string;
          decided_at?: string | null;
          decided_notes?: string | null;
          id?: string;
          payload: Json;
          status?: string;
        };
        Update: {
          brief_id?: string;
          created_at?: string;
          decided_at?: string | null;
          decided_notes?: string | null;
          id?: string;
          payload?: Json;
          status?: string;
        };
        Relationships: [
          {
            foreignKeyName: "video_launch_packages_brief_id_fkey";
            columns: ["brief_id"];
            isOneToOne: false;
            referencedRelation: "video_briefs";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: {
      v_campaign_perf: {
        Row: {
          campaign_id: string | null;
          clicks: number | null;
          client_id: string | null;
          cpl_real: number | null;
          ctr: number | null;
          format: string | null;
          freq: number | null;
          id: string | null;
          impressions: number | null;
          leads_ghl: number | null;
          leads_meta: number | null;
          pulled_at: string | null;
          spend: number | null;
          verdict: Database["public"]["Enums"]["ad_verdict"] | null;
          verdict_reason: string | null;
          window_days: number | null;
        };
        Relationships: [];
      };
    };
    Functions: {
      gen_brief_id_human: { Args: { p_client_slug: string }; Returns: string };
      gen_video_brief_id_human: {
        Args: { p_client_slug: string };
        Returns: string;
      };
      show_limit: { Args: never; Returns: number };
      show_trgm: { Args: { "": string }; Returns: string[] };
    };
    Enums: {
      ad_verdict: "kill" | "watch" | "keep";
      brief_status:
        | "draft"
        | "posted"
        | "approved"
        | "approved_with_changes"
        | "rejected";
      broll_store_backend: "local" | "supabase";
      creative_type: "image" | "video";
      image_creative_status:
        | "draft"
        | "approved"
        | "rejected"
        | "live"
        | "killed";
      image_iteration_kind:
        | "generate"
        | "regenerate"
        | "annotate"
        | "comment"
        | "user_edit";
      iteration_author: "user" | "ekko";
      ratio: "1x1" | "9x16" | "16x9";
      service_type: "roofing" | "remodeling";
      sync_status: "running" | "ok" | "error";
      video_brief_status:
        | "draft"
        | "posted"
        | "approved"
        | "approved_with_changes"
        | "rejected";
      video_creative_status:
        | "draft"
        | "script_ready"
        | "voiceover_ready"
        | "broll_ready"
        | "composed"
        | "captioned"
        | "approved"
        | "rejected";
      video_iteration_kind:
        | "generate_script"
        | "regenerate_voiceover"
        | "search_broll"
        | "swap_broll"
        | "rerender"
        | "recaption"
        | "comment"
        | "user_edit";
    };
    CompositeTypes: Record<string, never>;
  };
};
