// This file is regenerated by `pnpm regen:types` after applying migrations.
// See db/migrations/ and run `supabase gen types typescript --linked > lib/supabase/types.gen.ts`.
export type Database = Record<string, never>;
